### ISSUE TITLE
Add Internal Module?

### ISSUE THREAD

**Issue by Chobbes** [spl/dlist#37]
I'd like to use this library, but in order to implement something (basically I need to lift a function [a] -> [a] to a DList a -> DList a function... I think I need the DL constructor. I think what I want to do is this:

```
myLift f = DL $ f . unDL
```

Unfortunately `DL` and `unDL` don't seem to be exposed. `unDL` is indirectly exposed with `apply`, but I don't see `DL` isn't exported by the module.

Is there a good way to efficiently do what I want to do? Without access to the constructor? Admittedly, I'm not much of a wizard at analyzing Haskell performance, so it's possible I'm missing something, but maybe it would make sense to expose `DL` in an internal module or something?

This relates to this old PR: https://github.com/spl/dlist/issues/4

I totally agree with not exporting it by default, but if I want to be unsafe, having the option would be nice :).

**Comment by spl** [comment]
I've gone back and forth myself about whether to export the `DList` constructor. The problem is that, if you use it directly, the burden is on you to prove the isomorphism between `DList a` and `[a]`. That is, you can't lift an arbitrary `[a] -> [a]` to `DList a`.

Would you mind elaborating more on the kind of thing you want to do?

**Comment by Chobbes** [comment]
Currently I have a library that is backed with normal lists. I want to make a version that uses DList to see if I get a performance improvement, but in order to keep the code as similar as possible I want to lift a function from lists to lists to a function on dlists to dlists (my library uses [a] -> [a] functions to implement a bunch of functions).

I have seen the use of internal modules on hackage, before:

https://stackoverflow.com/questions/9190638/how-why-and-when-to-use-the-internal-modules-pattern

and I'm wondering if this might be a good idea for the DList package. It's obvious that you're breaking the abstraction if you're using the internal module, but you can also get access to the constructors if you really need them to hack on something. Otherwise the only alternative is just to clone DList locally, which isn't ideal. I think the internal module solution could give us the best of both worlds :).

**Comment by spl** [comment]
Have your tried first using the [`DList` interface](https://hackage.haskell.org/package/dlist-0.8.0.7/docs/Data-DList.html)? That way, you don't need to worry about proving the isomorphism.

**Comment by phadej** [comment]
I also asked for `.Internal` module in https://github.com/spl/dlist/pull/30 a year ago.

My need (converting non-empty dlist into empty one) cannot be expressed with current safe interface, so I do lose performance.

**Comment by spl** [comment]
Thanks for the feedback, folks. This was implemented in #55 and is now available in [`dlist-1.0`](https://hackage.haskell.org/package/dlist-1.0). See the `readme.md` for more.
