### ISSUE TITLE
Implementation of `stimes` in `Semigroup` instance

### ISSUE THREAD

**Issue by JaSpa** [spl/dlist#42]
Hey, thanks for this library!

I was looking at the implementation and was wondering if there is a specific reason to use  a hand-written implementation for `stimes` instead of `Data.Semigroup.stimesMonoid`. If I look at it correctly `stimesMonoid` uses only a logarithmic number of `(<>)` and would be preferable to the current implementation. If this is case I can make a pull-request.

**Comment by spl** [comment]
> I was looking at the implementation and was wondering if there is a specific reason to use a hand-written implementation for `stimes` instead of `Data.Semigroup.stimesMonoid`.

I'm not aware of any reason.

> If I look at it correctly `stimesMonoid` uses only a logarithmic number of `(<>)` and would be preferable to the current implementation. If this is case I can make a pull-request.

That seems reasonable. One thing that occurs to me is that it would be preferable to keep the existing error message instead of the `stimesMonoid` message. A PR would be welcome!

**Comment by spl** [comment]
Now available in [`dlist-1.0`](https://hackage.haskell.org/package/dlist-1.0).
