### ISSUE TITLE
Running the testsuite reports `Prelude.read: no parse`

### ISSUE THREAD

**Issue by andreasabel** [spl/dlist#96]
On current master, `cabal test` puts the following errors into the log:
```
*** Failed! Exception: 'Prelude.read: no parse' (after 1 test):
0 :| []
fromList "OverloadedStrings for DList:     success"
fromNonEmpty 'O' :| "verloadedStrings for DNonEmpty: success"
```
(However, the final result is printed as `Test suite test: PASS`.)

Source location: https://github.com/spl/dlist/blob/157a97db62d7780e6793408b0bf408a11cd36f22/tests/OverloadedStrings.hs#L26-L31

**Comment by spl** [comment]
Thanks! It's unfortunate that the exception does not cause the tests to fail.
